import { Helmet } from "react-helmet";
import { Link } from "wouter";
import { Shield } from "lucide-react";

export default function TermsPage() {
  return (
    <>
      <Helmet>
        <title>Terms of Use - SecurePass Pro</title>
        <meta
          name="description"
          content="Terms of Use for SecurePass Pro — free online password generator & checker. Read about acceptable use, warranties, and liability."
        />
      </Helmet>

      <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 transition-colors">

        <main className="max-w-4xl mx-auto px-4 py-10">
          <section className="prose dark:prose-invert max-w-none">
            <p className="text-sm text-slate-500 dark:text-slate-400">
              Last updated: August 12, 2025
            </p>

            <h2>Welcome</h2>
            <p>
              These Terms of Use govern your access to and use of SecurePass Pro
              (the "Service") available at{" "}
              <Link href="/">
                <a className="text-primary">SecurePass Pro</a>
              </Link>
              . By using the Service you agree to these terms. If you do not
              agree, do not use the Service.
            </p>

            <h3>1. Nature of Service</h3>
            <p>
              SecurePass Pro provides an online password generator and password
              strength checking tools. The Service is provided free of charge
              for personal and non-commercial use unless otherwise specified.
            </p>

            <h3>2. Local Processing & No Storage</h3>
            <p>
              All password generation and strength analysis are performed
              locally in your browser. We do not store, transmit, or log
              passwords generated by you. We cannot recover or retrieve
              passwords you generate.
            </p>

            <h3>3. Acceptable Use</h3>
            <p>
              You agree not to use the Service for unlawful activities or to
              harm others. You will not attempt to reverse engineer, exploit,
              interfere with, or compromise the security of the Service.
            </p>

            <h3>4. No Warranty</h3>
            <p>
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE
              DO NOT GUARANTEE THAT GENERATED PASSWORDS ARE UNBREAKABLE OR THAT
              THE SERVICE IS ERROR-FREE.
            </p>

            <h3>5. Limitation of Liability</h3>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, SECUREPASS PRO AND ITS
              AFFILIATES WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, OR
              CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>

            <h3>6. Changes to the Terms</h3>
            <p>
              We may update these Terms from time to time. We will post the
              updated terms here with a revised "Last updated" date. Continued
              use after changes constitutes acceptance.
            </p>

            <h3>7. Termination</h3>
            <p>
              We may suspend or terminate access to the Service at any time for
              any reason. Sections that by their nature survive termination
              (e.g., disclaimers, limitation of liability) will continue to
              apply.
            </p>

            <h3>8. Contact</h3>
            <p>
              For questions about these Terms, please contact us at:{" "}
              <a
                href="mailto:privacy@securepass-pro.vercel.app"
                className="text-primary"
              >
                privacy@securepass-pro.vercel.app
              </a>
              .
            </p>
          </section>
        </main>

        <footer className="bg-gray-900 text-gray-300 py-6 text-center text-sm">
          <p>
            © {new Date().getFullYear()} SecurePass Pro.{" "}
            <Link href="/privacy">
              <a className="underline hover:text-white">Privacy Policy</a>
            </Link>
          </p>
        </footer>
      </div>
    </>
  );
}
